<?php
// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
$ref = $_GET['ref'];
$y = 1;
$x = $_GET["x"];

while($y <= $x) {
	
$ch = curl_init();
$random = rand(10000000,99999999);
curl_setopt($ch, CURLOPT_URL, 'http://api.dealioapps.com/api/users/edit/0?access_token=no&app=1');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "firstname=Muhammad+Raisya&lastname=Zhaafir$random&username=Muhammad$random%40gmail.com&password=Muhammad$random%40&email=Muhammad$random%40gmail.com&phone=%2B62812$random&dob=17-Apr-1981&smoker=ya&gender=pria&roles%5B%5D=&active=1&player_id=&avatar=&state=Bengkulu&country_code=%2B62&register_type=custom&referred_by=$ref&app_version=3");
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_ENCODING, 'gzip, deflate');

$headers = array();
$headers[] = 'Host: api.dealioapps.com';
$headers[] = 'Cache-Control: max-age=0';
$headers[] = 'Upgrade-Insecure-Requests: 1';
$headers[] = 'Origin: null';
$headers[] = 'User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36';
$headers[] = 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8';
$headers[] = 'Accept-Language: id-ID,id;q=0.9,en-US;q=0.8,en;q=0.7';
$headers[] = 'Content-Type: application/x-www-form-urlencoded';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
echo "$y";
echo $result;
echo "<br>";
$y++;
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close ($ch);

}
?>